### ISSUE TITLE
Most of the company links in README.md are broken

### ISSUE THREAD

**Issue by tfsJoe** [palestinereacts/ethical-tech#1]
For example if you click Nvidia, you get a 404.

**Comment by palestinereacts** [comment]
Hey @tfsJoe thanks for creating this issue.

I have created a scaffold with the list of companies that I had in mind and wanted to add a readme for them later. Now I got around that, and I have fixed all the links and added context. 

Let me know if it looks good to you now so we can close the issue 👍

**Comment by tfsJoe** [comment]
Fixed, can close
